<a href="https://colab.research.google.com/github/kumaradityabtps/Learning-PyTorch-from-scratch/blob/main/PT_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensor DataTypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [4]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #  what datatype is tensors
                               device=None, # what device is yours tensor on
                               requires_grad=False) # whether or not to track gradients
float_32_tensor


tensor([3., 6., 9.])

In [5]:
float_32_tensor.dtype

torch.float32

In [6]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [8]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [9]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from tensors

1. Tensors not right datatype - to get datatype from a tensor , can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device, can use `tensor.device`

In [10]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9467, 0.8983, 0.1480, 0.8498],
        [0.6920, 0.6327, 0.2664, 0.7915],
        [0.7466, 0.3595, 0.7648, 0.8380]])

In [12]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9467, 0.8983, 0.1480, 0.8498],
        [0.6920, 0.6327, 0.2664, 0.7915],
        [0.7466, 0.3595, 0.7648, 0.8380]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


 ### Manipulating Tensors (tensor operations)

 Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication (elementt-wise)
 * Matrix Multiplication

In [20]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [21]:
# Multiply tensor by 10
tensor*10


tensor([10, 20, 30])

In [22]:
tensor

tensor([1, 2, 3])

In [23]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [24]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [25]:
torch.add(tensor, 10)

tensor([11, 12, 13])