<a href="https://colab.research.google.com/github/kumaradityabtps/Learning-PyTorch-from-scratch/blob/main/PT_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


### Matrix Multiplication

Thre as 2 ways:-
1. Element-wise Multiplication
2. Matrix Multiplication

There are two main rules to satisfy:
1. The **inner Dimensions** must match:
 * `(3,2) @ (3,2)` wont work
 * `(2,3) @ (3,2)` will work
 * `(3,2) @ (2,3)` will work

2. The Resulting matrix has the  shape of **outer dimensions**:
 * `(2, 3) @ (3, 2) -> (2, 2)`
 * `(3, 2) @ (2, 3) -> (3, 3)`

In [5]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.0672, 0.3239, 0.0151, 0.3985],
        [0.6785, 0.8232, 0.5043, 0.8169],
        [0.0794, 0.0709, 0.0627, 0.0623]])

In [2]:
# Element wise

tensor = torch.tensor([1, 2, 3])

In [3]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [4]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [5]:
# matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [6]:
%%time
value =0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 2.06 ms, sys: 11 µs, total: 2.07 ms
Wall time: 6.89 ms


In [7]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 107 µs, total: 107 µs
Wall time: 113 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [6]:
# Shhapes for matrix multiplications
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [8]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using **transpose**
A **transpose** switches the axes or dimensiond of a given tensoR

In [9]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [10]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [11]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [14]:
#The matrix multilpication operation
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [15]:

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
